### ISSUE TITLE
Create project nologis/forms

### ISSUE THREAD

**Issue by osedoe** [Nologis/ui-components#128]
Due the increasing size of this project, I think we need to split part of this repo into a forms  category and review the components so we can adapt it to the incoming design and needs.

**Comment by raulanatol** [comment]
@RichardMoralesLuis podrías echarle un ojo a esta tarea low-priority.
También habría que pasar este proyecto por project.config.utils, quitar travis y meter jenkins, etc.

**Comment by osedoe** [comment]
@RichardMoralesLuis y yo acabamos de caer. Vamos a intentar meter este proyecto ya en Nexus?

**Comment by raulanatol** [comment]
No todavía no ;)

**Comment by RichardMoralesLuis** [comment]
Ya se puede cerrar esta issue 😄
